### ISSUE TITLE
Missing `ots.secret.exs` file

### ISSUE THREAD

**Issue by kianmeng** [xinz/ex_aliyun_ots#20]
When running the `mix deps.get` command, got this error:

```
$ mix deps.get
** (File.Error) could not read file "/home/foobar/ex_aliyun_ots/config/ots.secret.exs": no such file or directory
    (elixir 1.11.1) lib/file.ex:354: File.read!/1
    (elixir 1.11.1) lib/config.ex:240: Config.__import__!/1
    (mix 1.11.1) lib/mix/config.ex:161: anonymous fn/2 in Mix.Config.__import__!/2
    (elixir 1.11.1) lib/enum.ex:2181: Enum."-reduce/3-lists^foldl/2-0-"/3
    (mix 1.11.1) lib/mix/config.ex:160: Mix.Config.__import__!/2
    (stdlib 3.13) erl_eval.erl:680: :erl_eval.do_apply/6
```

**Comment by xinz** [comment]
Hello, the `ots.secret.exs` is not submitted into the repo, here is a complete config for a sample.

```
use Mix.Config

config :ex_aliyun_ots, FooBarInstance,
  name: "xxx",
  endpoint: "xxx",
  access_key_id: "xxx",
  access_key_secret: "xxx"

config :ex_aliyun_ots,
  instances: [FooBarInstance],
  enable_tunnel: true
```

Thanks
