### ISSUE TITLE
Error running benchmark 

### ISSUE THREAD

**Issue by kianmeng** [xinz/ex_aliyun_ots#21]
Benchmarking doesn't work. Do we need actual Aliyun TableStore instance?

```
$ mix run benchmark/crc.exs
.....
** (Mix) Could not start application ex_aliyun_ots: exited in: ExAliyunOts.Application.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (ExAliyunOts.RuntimeError) Error: "Not found any instances configuration"
            (ex_aliyun_ots 0.9.0) lib/ex_aliyun_ots/application.ex:26: ExAliyunOts.Application.child_spec/3
            (ex_aliyun_ots 0.9.0) lib/ex_aliyun_ots/application.ex:16: ExAliyunOts.Application.start/2
            (kernel 7.0) application_master.erl:277: :application_master.start_it_old/4
```

**Comment by xinz** [comment]
Yes, we need to config the instance before that.
